DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 240
    BATCH_SIZE: 6 
    CROP_SIZE: 768
TEST:
    BATCH_SIZE: 1 
#    TEST_MODEL_PATH: trained_models/danet101_segmentron.pth

SOLVER:
    LR: 0.003

MODEL:
    MODEL_NAME: "DANet"
    BACKBONE: "resnet50"
    OUTPUT_STRIDE: 8
    DANET:
        MULTI_GRID: True
        MULTI_DILATION: [4, 8, 16]
